//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenTaker is the fastest way to share a screenshot and images without needing any downloads or installations. It’s designed with your workflow in mind by using only a minimum number of keypresses to share your images..
        /// </summary>
        internal static string ABOUTST_TEXT {
            get {
                return ResourceManager.GetString("ABOUTST_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Screen Taker.
        /// </summary>
        internal static string ABOUT_ST {
            get {
                return ResourceManager.GetString("ABOUT_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access by link.
        /// </summary>
        internal static string ACCESS_BY_LINK {
            get {
                return ResourceManager.GetString("ACCESS_BY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image owner has restricted access to this resource.
        /// </summary>
        internal static string ACC_DENIED_DESCR {
            get {
                return ResourceManager.GetString("ACC_DENIED_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate your account by confirming this email address.
        /// </summary>
        internal static string ACTIVATE {
            get {
                return ResourceManager.GetString("ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate now.
        /// </summary>
        internal static string ACTIVATE_NOW {
            get {
                return ResourceManager.GetString("ACTIVATE_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new folder.
        /// </summary>
        internal static string ADD_NEW_FOLDER {
            get {
                return ResourceManager.GetString("ADD_NEW_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        internal static string ALLOWED {
            get {
                return ResourceManager.GetString("ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        internal static string ALPHABET {
            get {
                return ResourceManager.GetString("ALPHABET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string ALREADY_HAVE_ACC {
            get {
                return ResourceManager.GetString("ALREADY_HAVE_ACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative :.
        /// </summary>
        internal static string ALTERNATIVE {
            get {
                return ResourceManager.GetString("ALTERNATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string AS_NEW_USER {
            get {
                return ResourceManager.GetString("AS_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated email. .
        /// </summary>
        internal static string AUTO {
            get {
                return ResourceManager.GetString("AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing full screen.
        /// </summary>
        internal static string CAPTURING_FS {
            get {
                return ResourceManager.GetString("CAPTURING_FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Print Screen key is your universal screen capture button. It’s located near the top right area of your keyboard, and is sometimes abbreviated to something like “Prt Scr”. You can use it anywhere. Just press it once and it’ll take a snapshot of whatever is curently on your screen and store it in your clipboard. Then, save it just open up ScreenTaker and paste it by pressing Upload image..
        /// </summary>
        internal static string CAPTURING_TEXT {
            get {
                return ResourceManager.GetString("CAPTURING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string CHANGE_PASS {
            get {
                return ResourceManager.GetString("CHANGE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your profile image.
        /// </summary>
        internal static string CHANGE_PROFILE_IMG {
            get {
                return ResourceManager.GetString("CHANGE_PROFILE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string CLASSIC {
            get {
                return ResourceManager.GetString("CLASSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation.
        /// </summary>
        internal static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm a new password.
        /// </summary>
        internal static string CONFIRM_PASS {
            get {
                return ResourceManager.GetString("CONFIRM_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string CONF_PASS {
            get {
                return ResourceManager.GetString("CONF_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account to keep track of your pasted images.
        /// </summary>
        internal static string CREATE_NEW_ACC {
            get {
                return ResourceManager.GetString("CREATE_NEW_ACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        internal static string DELETE_FOLDER {
            get {
                return ResourceManager.GetString("DELETE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        internal static string DELETE_IMAGE {
            get {
                return ResourceManager.GetString("DELETE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        internal static string DENIED {
            get {
                return ResourceManager.GetString("DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        internal static string DEVELOPED_BY {
            get {
                return ResourceManager.GetString("DEVELOPED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit groups.
        /// </summary>
        internal static string EDIT_GROUP {
            get {
                return ResourceManager.GetString("EDIT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit groups.
        /// </summary>
        internal static string EDIT_GROUPS {
            get {
                return ResourceManager.GetString("EDIT_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string ENTER_EMAIL {
            get {
                return ResourceManager.GetString("ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        internal static string ENTER_NEW_PASS {
            get {
                return ResourceManager.GetString("ENTER_NEW_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add yourself.
        /// </summary>
        internal static string ERR_ADD_YOURSELF {
            get {
                return ResourceManager.GetString("ERR_ADD_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with such email.
        /// </summary>
        internal static string ERR_EMAIL_NOT_EXIST {
            get {
                return ResourceManager.GetString("ERR_EMAIL_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        internal static string ERR_EMAIL_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_EMAIL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be empty.
        /// </summary>
        internal static string ERR_EMPTY_FIELD {
            get {
                return ResourceManager.GetString("ERR_EMPTY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is alredy a folder with this name.
        /// </summary>
        internal static string ERR_FOLDER_ALREDY {
            get {
                return ResourceManager.GetString("ERR_FOLDER_ALREDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is alredy a group with this name.
        /// </summary>
        internal static string ERR_GROUP_ALREDY {
            get {
                return ResourceManager.GetString("ERR_GROUP_ALREDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file should be image (BMP, JPEG, PNG or GIF).
        /// </summary>
        internal static string ERR_IMAGE_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_IMAGE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This right is inherited and can&apos;t be changed.
        /// </summary>
        internal static string ERR_INHERITED {
            get {
                return ResourceManager.GetString("ERR_INHERITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t make public image in private folder.
        /// </summary>
        internal static string ERR_PUBLIC_IN_PRIVATE {
            get {
                return ResourceManager.GetString("ERR_PUBLIC_IN_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERR_TITLE {
            get {
                return ResourceManager.GetString("ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is alredy here.
        /// </summary>
        internal static string ERR_USER_ALREDY {
            get {
                return ResourceManager.GetString("ERR_USER_ALREDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string FEATURES {
            get {
                return ResourceManager.GetString("FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an account to manage and delete your old images.
        ///Designed with power-users in mind, ScreenTaker has a fast workflow that requires only the minimum number of keypresses..
        /// </summary>
        internal static string FEATURES_TEXT {
            get {
                return ResourceManager.GetString("FEATURES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My folders.
        /// </summary>
        internal static string FOLDERS {
            get {
                return ResourceManager.GetString("FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        internal static string FOLDERY {
            get {
                return ResourceManager.GetString("FOLDERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string FORGOT_PASS {
            get {
                return ResourceManager.GetString("FORGOT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GROUPS {
            get {
                return ResourceManager.GetString("GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string GROUP_NAME {
            get {
                return ResourceManager.GetString("GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent mail to.
        /// </summary>
        internal static string HAVE_SENT {
            get {
                return ResourceManager.GetString("HAVE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you not got any mail.
        /// </summary>
        internal static string IF_NOT_GOT {
            get {
                return ResourceManager.GetString("IF_NOT_GOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string IMAGES {
            get {
                return ResourceManager.GetString("IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string IMAGEY {
            get {
                return ResourceManager.GetString("IMAGEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        internal static string INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string INVALID_LOGIN_ATTEMPT {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The easiest way to share your images..
        /// </summary>
        internal static string JUMBOTRON_TEXT {
            get {
                return ResourceManager.GetString("JUMBOTRON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LOGIN_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make private.
        /// </summary>
        internal static string MAKE_PRIVATE {
            get {
                return ResourceManager.GetString("MAKE_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        internal static string MAKE_PUBLIC {
            get {
                return ResourceManager.GetString("MAKE_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage access.
        /// </summary>
        internal static string MANAGE_ACCESS {
            get {
                return ResourceManager.GetString("MANAGE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage groups.
        /// </summary>
        internal static string MANAGE_GROUPS {
            get {
                return ResourceManager.GetString("MANAGE_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum lenght: 20 symbols.
        /// </summary>
        internal static string MAX_NAME_LENGTH {
            get {
                return ResourceManager.GetString("MAX_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MOVE {
            get {
                return ResourceManager.GetString("MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move here.
        /// </summary>
        internal static string MOVE_HERE {
            get {
                return ResourceManager.GetString("MOVE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move image to.
        /// </summary>
        internal static string MOVE_IMAGE {
            get {
                return ResourceManager.GetString("MOVE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NEW_FOLDER {
            get {
                return ResourceManager.GetString("NEW_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title for new folder.
        /// </summary>
        internal static string NEW_FOLDER_TITLE {
            get {
                return ResourceManager.GetString("NEW_FOLDER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NEW_PASS {
            get {
                return ResourceManager.GetString("NEW_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for cannot be found.
        /// </summary>
        internal static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OLD_PASS {
            get {
                return ResourceManager.GetString("OLD_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string OWNER {
            get {
                return ResourceManager.GetString("OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed..
        /// </summary>
        internal static string PASSWORD_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        internal static string PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password.
        /// </summary>
        internal static string PASSWORD_FORGOT {
            get {
                return ResourceManager.GetString("PASSWORD_FORGOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        internal static string PASSWORD_RESET {
            get {
                return ResourceManager.GetString("PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string PEOPLE {
            get {
                return ResourceManager.GetString("PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string PRIVATE {
            get {
                return ResourceManager.GetString("PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string PROFILE_HEAD {
            get {
                return ResourceManager.GetString("PROFILE_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RENAME {
            get {
                return ResourceManager.GetString("RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new title for folder.
        /// </summary>
        internal static string RENAME_TITLE {
            get {
                return ResourceManager.GetString("RENAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new title for image.
        /// </summary>
        internal static string RENAME_TITLE_IMAGE {
            get {
                return ResourceManager.GetString("RENAME_TITLE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation mail again.
        /// </summary>
        internal static string RESEND_AGAIN {
            get {
                return ResourceManager.GetString("RESEND_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this {0} default.
        /// </summary>
        internal static string RESET_PASSWORD_EMAIL {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Log in.
        /// </summary>
        internal static string RETURN_TO_LOGIN {
            get {
                return ResourceManager.GetString("RETURN_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved as.
        /// </summary>
        internal static string SAVED_AS {
            get {
                return ResourceManager.GetString("SAVED_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string SEARCH_FOR {
            get {
                return ResourceManager.GetString("SEARCH_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to me.
        /// </summary>
        internal static string SHARED_FOLDERS {
            get {
                return ResourceManager.GetString("SHARED_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share folder.
        /// </summary>
        internal static string SHARE_FOLDER {
            get {
                return ResourceManager.GetString("SHARE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share link.
        /// </summary>
        internal static string SHARE_LINK {
            get {
                return ResourceManager.GetString("SHARE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SIGNIN_LOGOUT {
            get {
                return ResourceManager.GetString("SIGNIN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry ....
        /// </summary>
        internal static string SORRY {
            get {
                return ResourceManager.GetString("SORRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сongratulation.
        /// </summary>
        internal static string SUCCESS_COPY {
            get {
                return ResourceManager.GetString("SUCCESS_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link successfully copied.
        /// </summary>
        internal static string SUCCESS_COPY_TEXT {
            get {
                return ResourceManager.GetString("SUCCESS_COPY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to confirm of validity of your email address. After receiving the mail follow the link provided to complete your registration.
        /// </summary>
        internal static string TO_CONFIRM {
            get {
                return ResourceManager.GetString("TO_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to homepage.
        /// </summary>
        internal static string TO_MAIN_PAGE {
            get {
                return ResourceManager.GetString("TO_MAIN_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string TURN_OFF {
            get {
                return ResourceManager.GetString("TURN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TURN_ON {
            get {
                return ResourceManager.GetString("TURN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UPLOAD {
            get {
                return ResourceManager.GetString("UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        internal static string UPLOAD_IMAGE {
            get {
                return ResourceManager.GetString("UPLOAD_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new image.
        /// </summary>
        internal static string UPLOAD_NEW_IMAGE {
            get {
                return ResourceManager.GetString("UPLOAD_NEW_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your account to log in.
        /// </summary>
        internal static string USE_ACCOUNT {
            get {
                return ResourceManager.GetString("USE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete .
        /// </summary>
        internal static string WANT_DELETE {
            get {
                return ResourceManager.GetString("WANT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password.
        /// </summary>
        internal static string YOUR_OLD_PASS {
            get {
                return ResourceManager.GetString("YOUR_OLD_PASS", resourceCulture);
            }
        }
    }
}
