//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenTaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupShare
    {
        public int GroupId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public int Id { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual PersonGroup PersonGroup { get; set; }
        public virtual Image Image { get; set; }
    }
}
