//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenTaker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScreenTakerDBEntities : DbContext
    {
        public ScreenTakerDBEntities()
            : base("name=ScreenTakerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<folder> folder { get; set; }
        public virtual DbSet<groupShare> groupShare { get; set; }
        public virtual DbSet<image> image { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<personGroup> personGroup { get; set; }
        public virtual DbSet<tag> tag { get; set; }
        public virtual DbSet<userShare> userShare { get; set; }
    }
}
