//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenTaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShare
    {
        public Nullable<int> personId { get; set; }
        public Nullable<int> imageId { get; set; }
        public Nullable<int> folderId { get; set; }
        public string email { get; set; }
        public int id { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Image Image { get; set; }
        public virtual Person Person { get; set; }
    }
}
